### ISSUE TITLE
Release version 1.0 to Sonatype OSS Nexus

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nmdp-bioinformatics/genotype-list#113]
```
Release version 1.0 to Sonatype OSS Nexus.

```

Original issue reported on code.google.com by `mhe...@nmdp.org` on 17 Jul 2013 at 6:54
* Blocking: #132
* Blocked on: #9, #114, #119

**Comment by mheuer-nmdp** [comment]
Fixed by commit 0cfd132df4a41c09a0d373b43b696740f580a223
